############################
## CHANGE THESE
############################

baseURL: 'https://www.sizhuang.org'
title: Sizhuang's website

############################
## MISC
############################

enableEmoji: true
disableKinds: ['taxonomy', 'term']
languageCode: 'en-us'


