############################
## Navbar
############################

main:
- name: Home
  url: /
  weight: 10
# - name: Blog
#   url: /blog/
#   weight: 20
- name: About
  url: /about/
  weight: 20
- name: News
  url: /news/
  weight: 30