############################
## Author
############################

author:
  name: Sizhuang He
  image: author.png
  greeting: "Welcome to the website of Sizhuang He!"
  icon: ":wave:"

############################
## Links
############################

links:
  - github: https://github.com/SizhuangHe
  # - link: https://github.com/SizhuangHe/personal_website#readme
  # - website: 
  - x-twitter: https://twitter.com/sizhuang_
  # - mastodon: 
  - linkedin: https://www.linkedin.com/in/sizhuanghe/
  # - instagram: 
  # - reddit: 
  # - telegram: 
  # - whatsapp: 
  # - signal: 
  # - codepen: 
  # - dev: 
  # - email: 
  # - discord: 
  # - orcid: 
  # - slack: 
  # - stack-overflow: 
  # - twitch: 
  # - patreon: 
  # - soundcloud: 
  # - dribbble: 
  # - stack-exchange: 
  # - tiktok: 
  # - youtube: 
  # - keybase: 
  # - flickr: 
  # - tumblr: 
  # - kickstarter: 
  # - snapchat:
  # - bluesky: 
  # - bitbucket: 
  # - bandcamp: 
  # - etsy: 
  # - spotify: 
  # - pinterest: 
  # - strava: 
  # - untappd: 
  # - skype: 
  # - medium: 
  # - foursquare: 
  # - apple: 
  # - amazon:
  # - google:
  # - paypal:
  # - windows:

###############################
## OpenGraph & Twitter Cards
###############################

title: personal_website
description: "Site build with Qubt & Hugo"
images:
  - thumbnail.png
